
package_json(
   name = "pkg",
   scripts = [
      node_build_script(entry_point = "package", output_directories = ["./dist"])
   ],
   dependencies =[
      "./src:index_html",
      "./src:js",
      "//lib/46f3984c15cda1c6:pkg",
   ]
)
